name: MLOpsDemoTest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZ_CS: ${{ secrets.CONN_STR_AZDLAT }}
        run: |
          pip install wget
          pip install sklearn
          pip install pandas
          pip install seaborn
          pip install matplotlib
          pip install dvc
          pip install dvc[azure]
          
          echo "Hello"
          echo ${{env.AZ_CS}}
          
          echo "123"
          echo ${{ secrets.CONN_STR_AZDLAT }}
          
          echo "1234"
          echo ${ secrets.CONN_STR_AZDLAT }

          dvc remote modify --local myremote connection_string env.AZ_CS
          
          dvc pull
          dvc repro
          
          git fetch --prune
          dvc metrics diff --show-md main > report.md
                    
          echo "## Metrics"
          cat metrics.json
          
          cml-publish metrics.json >> report.md
          echo "## Validating results by region"
          cml-publish by_region.png --md >> report.md 
          cml-send-comment report.md
